sudo: false
dist: xenial
language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - cmake

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi

script:
  - mkdir build
  - cd build
  - gcc -v && g++ -v && cmake --version
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
